
name = "LearningObserverComponents"
uuid = "1b08a953-4be3-4667-9a23-ae02e7b51076"
authors = ["Bradley Erickson <bbwe24@gmail.com>"]
version = "0.0.1"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compat]
julia = "1.2"
Dash = "0.1.3, 1.0"
